// @ts-check

/**
 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  getstartedSidebar: [{type: 'autogenerated', dirName: 'get-started'}],
  coreconceptsSidebar: [{type: 'autogenerated', dirName: 'core-concepts'}],
  workflowsSidebar: [{type: 'autogenerated', dirName: 'workflows'}],
  walkthroughsSidebar: [{type: 'autogenerated', dirName: 'walkthroughs'}],
};

export default sidebars;
